rootProject.name = 'VlogNetworkApp'
apply from: file("../node_modules/@react-native/gradle-plugin/settings.gradle")
includeBuild('../node_modules/@react-native/gradle-plugin')

include ':app'
includeBuild('../node_modules/react-native-gradle-plugin')

if (settings.hasProperty("newArchEnabled") && settings.newArchEnabled == "true") {
    include(":ReactAndroid")
    project(":ReactAndroid").projectDir = file('../node_modules/react-native/ReactAndroid')
}
