# Server Configuration
server.port=8080

# Application Name
spring.application.name=network-backend

# Logging
logging.level.root=INFO
logging.level.com.vlog.network=DEBUG

# WebFlux Configuration
spring.webflux.base-path=/
